#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sqlite3
import os
import sys

dire =""
dire= os.getcwdb()

print ("la direccion donde se esta generando la base de dato es: \n", dire)

try
    conn = sqlite3.connect('lecturas.db')
    cursor =conn.cursor()
    
    cursor.execute('''CREATE TABLE lecturas_
    (ID_LECTURA PRIMARY KEY NOT NULL,
    __date TEXT,
    _time TEXT,
    watts_now INTEGER,
    day_kmh	INTEGER,
    total_kmh INTEGER)''')

    print ("LA BASE DE DATOS A SIDO CREADA \n ")
               
    conn.commit()
    
    except sqlite3.OperationalError as error:
    print ("la Base de datos ya existe ")
cursor.close()
conn.close()

print ("podemos usarlo")
